version: '3'

networks:
  base:
    driver: bridge

services:
  telegramBot:
    container_name: telegrambot
    image: php:8.0-apache
    volumes:
      - ./public:/var/www/html/
    ports:
      - 8200:80
    networks:
      - base